### ISSUE TITLE
Task list for multimedia update

### ISSUE THREAD

**Issue by ErmitaVulpe** [ErmitaVulpe/orlicz#27]
- [x] "fill the sides"
- [x] change the first youtube wideo
- [x] "fix" png description
- [x] change .jpg to jpeg
- [x] change code embeds
