### ISSUE TITLE
Task list for multimedia update 2

### ISSUE THREAD

**Issue by ErmitaVulpe** [ErmitaVulpe/orlicz#31]
## I hate this motherfukcer. Every change he requires makes everything worse
I give up. I won't fight no more, I'll do as he says.

- [ ] implement google ads
- [ ] bigger video embeds
- [ ] code embeds same width (WHYYYY)
- [ ] add an audio from a remote file
- [ ] change Bermuda Triangle to points
- [ ] alt and title for images
- [ ] image description with full English name
- [ ] png with transparency
- [ ] in "Osadzanie grafiki z plików lokalnych" add to description: "Oto kilka najpopularniejszych formatów"
- [ ] in jpeg add "lossy compression", in png and gif add "lossless compression"
- [ ] change YouTube embed mistake to audio embed as well as give a solution to it
- [ ] change "mapa z pineską" to "lokalizacja Technikum elektroniczne nr.1"
- [ ] change "mapa z charakterystycznym punktem" to Znana ulica w Grabowcu
- [ ] remove "mapa" from google maps mid sections
- [ ] add a map with a walking path between two points in a city
- [ ] zoom out bike path map
- [ ] add description with logo for external service (I.e. Google maps, Spotify)
